croissants:
  - name: Classic Croissant
    image: /assets/images/croissant1.jpg
  - name: Almond Croissant
    image: /assets/images/croissant.jpg
  - name: Almond Croissant
    image: /assets/images/croissant.jpg
  - name: Chocolate Croissant
    image: /assets/images/croissant2.jpg

cookies:
  - name: Almond Cookies
    image: /assets/images/croissant.jpg
  - name: Almond Croissant
    image: /assets/images/croissant.jpg
  - name: Almond Croissant
    image: /assets/images/croissant.jpg
  - name: Classic Cookies
    image: /assets/images/croissant1.jpg
  - name: Chocolate Cookies
    image: /assets/images/croissant2.jpg

breads:
  - name: Sourdough
    image: /assets/images/croissant.jpg
  - name: Raisin Bread
    image: /assets/images/croissant1.jpg
  - name: Focaccia
    image: /assets/images/croissant2.jpg
  - name: Baguette
    image: /assets/images/croissant2.jpg
